version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_HOSTNAME: mongo
